/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iu;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Luiz
 */
public class iuPrincipal extends javax.swing.JFrame {
    private int controle = 0;   //variavel de controle para funçoes do programa
    private int x1, x2, y1, y2; //variaveis de posicao do mouse
    private int aux = 0;    //var para acesso de funçoes em duas etapas
    private Color cor = Color.BLACK;      //cor provinda da paleta de cores
    private iuPaleta paleta = new iuPaleta();
    /**
     * Creates new form iuPrincipal
     */
    public iuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpDesenho = new javax.swing.JPanel();
        jrLinha = new javax.swing.JRadioButton();
        jrCirculo = new javax.swing.JRadioButton();
        jrLivre = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jpDesenho.setBackground(new java.awt.Color(255, 255, 255));
        jpDesenho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpDesenhoMouseDragged(evt);
            }
        });
        jpDesenho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpDesenhoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpDesenhoLayout = new javax.swing.GroupLayout(jpDesenho);
        jpDesenho.setLayout(jpDesenhoLayout);
        jpDesenhoLayout.setHorizontalGroup(
            jpDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );
        jpDesenhoLayout.setVerticalGroup(
            jpDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        buttonGroup1.add(jrLinha);
        jrLinha.setText("Linha");

        buttonGroup1.add(jrCirculo);
        jrCirculo.setText("Círculo");

        buttonGroup1.add(jrLivre);
        jrLivre.setSelected(true);
        jrLivre.setText("Desenho Livre");

        jMenu1.setText("Funções");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Mudar Cor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrLinha)
                    .addComponent(jrCirculo)
                    .addComponent(jrLivre))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrLinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrCirculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrLivre))
                    .addComponent(jpDesenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpDesenhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDesenhoMouseClicked
        cor = paleta.getCor();
        if (jrLinha.isSelected())
            pintarReta(jpDesenho.getGraphics(), evt.getX(), evt.getY());
        else if (jrCirculo.isSelected())
            pintarCirculo(jpDesenho.getGraphics(), evt.getX(), evt.getY());
    }//GEN-LAST:event_jpDesenhoMouseClicked

    private void jpDesenhoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDesenhoMouseDragged
        cor = paleta.getCor();
        if(jrLivre.isSelected())
                pintar(jpDesenho.getGraphics(), evt.getX(), evt.getY());
    }//GEN-LAST:event_jpDesenhoMouseDragged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        paleta.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iuPrincipal().setVisible(true);
            }
        });
    }
    
    void pintarReta(Graphics g, int x, int y){
        if(aux == 0){
            x1 = x;
            y1 = y;
            aux = 1;
        } else{
            x2 = x;
            y2 = y;
            aux = 0;
            g.setColor(cor);
            g.drawLine(x1, y1, x2, y2);
        }
    }
    
    void pintarCirculo(Graphics g, int x, int y){
        g.setColor(cor);
        g.drawOval(x, y, 6, 6);
    }
    
    void pintar(Graphics g, int x, int y){  //pintando um pixel
        g.setColor(cor);
        g.drawLine(x, y, x, y);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jpDesenho;
    private javax.swing.JRadioButton jrCirculo;
    private javax.swing.JRadioButton jrLinha;
    private javax.swing.JRadioButton jrLivre;
    // End of variables declaration//GEN-END:variables
}
